routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [\App\Http\Controllers\HomeController::class,'index'])->name('home');

Route::post('/keranjang', [\App\Http\Controllers\ControllerKeranjang::class,'store'])->name('keranjang.store');
Route::patch('/keranjang/{keranjang}', [\App\Http\Controllers\ControllerKeranjang::class,'update'])->name('keranjang.update');
Route::delete('/keranjang/{keranjang}',[\App\Http\Controllers\ControllerKeranjang::class,'delete'])->name('keranjang.delete');

Route::post('/transaksi',[\App\Http\Controllers\ControllerTransaksi::class,'store'])->name('transaksi.store');
Route::get('/transaksi',[\App\Http\Controllers\ControllerTransaksi::class,'index'])->name('transaksi.index');
Route::get('/transaksi/{transaksis}',[\App\Http\Controllers\ControllerTransaksi::class,'show'])->name('transaksi.show');


Route::resource('items',\App\Http\Controllers\ItemController::class);
Route::get('/items/{id}/destroy',[\App\Http\Controllers\ItemController::class,'destroy'])->name('items.destroy');

Route::resource('categories',\App\Http\Controllers\CategoryController::class);
Route::get('/categories/{id}/destroy',[\App\Http\Controllers\CategoryController::class,'destroy'])->name('categories.destroy');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\KategoriItem;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = KategoriItem::all();

        view()->share([
            'items' => $items
        ]);
        return view('category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new KategoriItem();
        $data->nama = $request->nama;

        $data->save();
         return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = KategoriItem::find($id);
        view()->share([
           'data' => $data
        ]);

        return view('category.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = KategoriItem::find($id);
        $data->nama = $request->nama;

        $data->save();
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = KategoriItem::find($id);

        $data->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/category/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5>Item</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <form class="col s12" action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="nama" name="nama" type="text" class="validate">
                            <label for="name">Name</label>
                        </div>
                    </div>
                    <button class="waves-effect waves-light btn" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5>Item</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <form class="col s12" action="{{route('categories.update',$data->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="nama" name="nama" value="{{$data->nama}}" type="text" class="validate">
                            <label for="name">Name</label>
                        </div>
                    </div>
                    <button class="waves-effect waves-light btn" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h5>Item</h5>
                <a href="{{route('categories.create')}}" class="waves-effect waves-light btn text-white ">Tambah</a>
            </div>
            <div class="card-body">
                <table >
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">Nama Roti</th>
                        <th scope="col">action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($items as $item)
                        <tr>
                            <th scope="col">{{$loop->iteration}}</th>
                            <td>{{$item->nama}}</td>
                            <td><a href="{{route('categories.edit',$item->id)}}" class="waves-effect waves-light btn text-white blue lighten-1">Edit</a>
                                <a href="{{route('categories.destroy',$item->id)}}" class="waves-effect waves-light btn red text-white">Delete</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>



@endsection