routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [\App\Http\Controllers\HomeController::class,'index'])->name('home');

Route::post('/keranjang', [\App\Http\Controllers\ControllerKeranjang::class,'store'])->name('keranjang.store');
Route::patch('/keranjang/{keranjang}', [\App\Http\Controllers\ControllerKeranjang::class,'update'])->name('keranjang.update');
Route::delete('/keranjang/{keranjang}',[\App\Http\Controllers\ControllerKeranjang::class,'delete'])->name('keranjang.delete');

Route::post('/transaksi',[\App\Http\Controllers\ControllerTransaksi::class,'store'])->name('transaksi.store');
Route::get('/transaksi',[\App\Http\Controllers\ControllerTransaksi::class,'index'])->name('transaksi.index');
Route::get('/transaksi/{transaksis}',[\App\Http\Controllers\ControllerTransaksi::class,'show'])->name('transaksi.show');


Route::resource('items',\App\Http\Controllers\ItemController::class);
Route::get('/items/{id}/destroy',[\App\Http\Controllers\ItemController::class,'destroy'])->name('items.destroy');

Route::resource('categories',\App\Http\Controllers\CategoryController::class);
Route::get('/categories/{id}/destroy',[\App\Http\Controllers\CategoryController::class,'destroy'])->name('categories.destroy');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Toko Roti</title>
    <link rel="icon" type="image/png" href="{{ asset('image/amanda.jpg')  }}">
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->

    <link href="{{asset('css/font.css')}}" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <script src="{{asset('js/materialize.min.js')}}"></script>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/materialize.css') }}" rel="stylesheet">
    <script src="{{ asset('js/jquery-2.1.1.min.js') }}"></script>

<script>
    $(document).ready(function(){
        $('.materialboxed').materialbox();
    });
</script>

</head>
<body>
    <div id="app">
        <nav>
            <div class="container">
                <a class="brand-logo" style="text-decoration: none" href="{{ url('/') }}">
                    Roti Krian
                </a>


                <div class="nav-wrapper" id="navbarSupportedContent">

                    <!-- Right Side Of Navbar -->
                    <ul class="right hide-on-med-and-down" id="nav-mobile">
                        <!-- Authentication Links -->
                        @guest
                            <li><a style="color: white; text-decoration: none" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            @if (Route::has('register'))
                                <li><a style="color: white; text-decoration: none" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" style="color: white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('transaksi.index') }}">Log Transaksi</a>
                                    <a class="dropdown-item" href="{{ route('items.index') }}">Input Item</a>
                                    <a class="dropdown-item" href="{{ route('categories.index') }}">Input Kategori</a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>


</body>
</html>